import { FluidConfig, Preset } from './types';

export const DEFAULT_CONFIG: FluidConfig = {
  simResolution: 128,
  dyeResolution: 1024,
  densityDissipation: 3.5,
  velocityDissipation: 2.0,
  pressure: 0.1,
  pressureIterations: 20,
  curl: 30, // Higher swirl gives lively organic vortices
  splatRadius: 0.25,
  splatForce: 6000,
  shading: true,
  colorUpdateSpeed: 10,
  hoverSplat: true,
  clickSplat: true,
  backgroundColor: '#000000',
  transparent: true,
  colorMode: 'rainbow',
  customColor: '#00ffcc',
  ambientMotion: true,
  bloomEffect: true,
};

export const PRESETS: Preset[] = [
  {
    id: 'rainbow',
    name: 'Spectral Rainbow',
    description: 'Dynamic multi-hue chromatic spectrum that flows with your motion.',
    badge: 'Default',
    previewGradient: 'linear-gradient(135deg, #ff0055, #ff9900, #00ffcc, #3366ff)',
    config: {
      colorMode: 'rainbow',
      curl: 30,
      densityDissipation: 3.2,
      velocityDissipation: 2.0,
      splatRadius: 0.25,
      shading: true,
      splatForce: 6000,
    },
  },
  {
    id: 'neon',
    name: 'Cyberpunk Neon',
    description: 'High-voltage electric cyan, hot magenta, and hyper violet.',
    badge: 'Vibrant',
    previewGradient: 'linear-gradient(135deg, #00f0ff, #ff0077, #7928ca)',
    config: {
      colorMode: 'neon',
      curl: 36,
      densityDissipation: 3.0,
      velocityDissipation: 1.8,
      splatRadius: 0.28,
      shading: true,
      splatForce: 6500,
    },
  },
  {
    id: 'chrome',
    name: 'Liquid Chrome',
    description: 'Glossy mercury fluid with 3D light reflections and metallic sheen.',
    badge: '3D Gloss',
    previewGradient: 'linear-gradient(135deg, #ffffff, #94a3b8, #334155, #f8fafc)',
    config: {
      colorMode: 'chrome',
      curl: 22,
      densityDissipation: 2.4,
      velocityDissipation: 1.6,
      splatRadius: 0.3,
      shading: true,
      splatForce: 5500,
    },
  },
  {
    id: 'cosmic',
    name: 'Deep Cosmic',
    description: 'Deep nebula purples, astral indigos, and celestial blues.',
    badge: 'Astral',
    previewGradient: 'linear-gradient(135deg, #4c1d95, #6d28d9, #2563eb, #ec4899)',
    config: {
      colorMode: 'cosmic',
      curl: 32,
      densityDissipation: 3.4,
      velocityDissipation: 2.1,
      splatRadius: 0.26,
      shading: true,
      splatForce: 6200,
    },
  },
  {
    id: 'fire',
    name: 'Solar Flare',
    description: 'Molten magma, blazing gold, and crimson solar bursts.',
    badge: 'Intense',
    previewGradient: 'linear-gradient(135deg, #ff4500, #ff8c00, #ffd700, #ff1493)',
    config: {
      colorMode: 'fire',
      curl: 38,
      densityDissipation: 3.8,
      velocityDissipation: 2.2,
      splatRadius: 0.27,
      shading: true,
      splatForce: 7000,
    },
  },
  {
    id: 'emerald',
    name: 'Emerald Aurora',
    description: 'Boreal jade, electric mint, and luminous lime auroras.',
    badge: 'Organic',
    previewGradient: 'linear-gradient(135deg, #059669, #10b981, #34d399, #06b6d4)',
    config: {
      colorMode: 'emerald',
      curl: 28,
      densityDissipation: 3.2,
      velocityDissipation: 2.0,
      splatRadius: 0.25,
      shading: true,
      splatForce: 6000,
    },
  },
  {
    id: 'smoke',
    name: 'Ethereal Smoke',
    description: 'Delicate silky white smoke plumes drifting like silk.',
    badge: 'Minimal',
    previewGradient: 'linear-gradient(135deg, #ffffff, #cbd5e1, #64748b)',
    config: {
      colorMode: 'smoke',
      curl: 25,
      densityDissipation: 2.6,
      velocityDissipation: 1.8,
      splatRadius: 0.32,
      shading: false,
      splatForce: 5000,
    },
  },
];
